### ISSUE TITLE
题目悬浮在最上面好显眼

### ISSUE THREAD

**Issue by yangshuai726** [yuyuanweb/mianshiya-plugin#3]
感觉摸鱼的时候，题目显示在最上面，好显眼。能不能加个设置，让题目不一直置顶显示。

**Comment by co-pine** [comment]
目前暂时还不支持设置，小伙伴可以下载老一点的版本，比如 0.5.0 ，题目不会一直置顶显示。链接：https://plugins.jetbrains.com/plugin/25258-mianshiya/versions
