### ISSUE TITLE
How to hot reload when developing a plugin in intelliJ?

### ISSUE THREAD

**Issue by hztBUAA** [yuyuanweb/mianshiya-plugin#4]
It seems that the `Plugin DevKit` doesn't work. And the only way for me to simultaneously watch the on-developing plugin is BY rerunning the ide instance, which spends a long time and is low-efficient. 

I have watched your tutorial videos in billibilli concerning your mianshiya-plugin project, and you mentioned the `Plugin DevKit`, but it seems can not satisfy my need.

I wonder if you know that how to implement hot reload in plugin development, just as convenient as in web application with explorers.

THANKS!

**Comment by co-pine** [comment]
目前我也没有找到太好的方案，建议您给官方发邮件进行询问
